#!/usr/bin/env python3
"""Generate dated local verification evidence; never infer production readiness."""
from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import re
import subprocess
import sys
import tempfile
import time
import xml.etree.ElementTree as ET
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.services.catalog import PRODUCTS


def source_files():
    for directory in ("app", "scripts", "tests", "supabase", ".github"):
        for path in sorted((ROOT / directory).rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts and ".temp" not in path.parts:
                yield path
    for path in sorted(ROOT.iterdir()):
        if path.is_file() and (path.suffix in {".md", ".txt", ".lock", ".ini"}
                              or path.name in {".env.example", ".dockerignore", "Dockerfile", ".gitignore"}):
            yield path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--baseline", type=Path, help="Optional preserved source directory to compare")
    parser.add_argument("--postgres", action="store_true", help="Run localhost-only PostgreSQL transaction checks")
    args = parser.parse_args()
    timestamp = datetime.now(UTC)
    output = args.output or ROOT / "release-generated" / f"verification-{timestamp:%Y%m%dT%H%M%SZ}.json"
    report = {
        "generated_at_utc": timestamp.isoformat(), "scope": "local source and disposable database checks only",
        "production_deployed": False, "live_provider_flow_verified": False,
        "python": sys.version.split()[0],
        "dependencies": {name: importlib.metadata.version(name) for name in ("fastapi", "starlette", "httpx", "pytest")},
        "catalog_entitlements": [{"kind": p.kind, "wallet_credits": p.wallet_credits,
                                  "venture_passes": p.venture_passes, "credits_per_pass": p.credits_per_pass} for p in PRODUCTS],
        "checks": [], "source_sha256": {}, "changed_from_baseline": [],
    }
    environment = os.environ.copy()
    environment.update(AUTH_MODE="local", STATE_BACKEND="local", WALLET_BACKEND="local", APP_ENV="development", BILLING_ENFORCED="0")
    with tempfile.TemporaryDirectory(prefix="killgate-verification-") as temp:
        junit = Path(temp) / "pytest.xml"
        commands = [
            ("pytest", [sys.executable, "-m", "pytest", "-q", f"--junitxml={junit}"]),
            ("ruff", [sys.executable, "-m", "ruff", "check", "app", "scripts", "tests", "--select", "F,B"]),
            ("compileall", [sys.executable, "-m", "compileall", "-q", "app", "scripts", "tests"]),
            ("javascript", ["node", "--check", "app/static/app.js"]),
            ("postgres_test_syntax", ["node", "--check", "scripts/check_release_postgres.cjs"]),
            ("pip_check", [sys.executable, "-m", "pip", "check"]),
            ("dependency_audit", [sys.executable, "-m", "pip_audit", "-r", "requirements.lock", "--disable-pip"]),
            ("bandit_medium_high", [sys.executable, "-m", "bandit", "-q", "-ll", "-r", "app", "scripts", "-x", "tests"]),
        ]
        if args.postgres:
            commands.append(("postgres_transactions", ["node", "scripts/check_release_postgres.cjs"]))
        for name, command in commands:
            started = time.monotonic()
            try:
                completed = subprocess.run(command, cwd=ROOT, env=environment, text=True, capture_output=True, timeout=300, check=False)
                check = {"name": name, "passed": completed.returncode == 0, "exit_code": completed.returncode,
                         "seconds": round(time.monotonic() - started, 2),
                         "output": (completed.stdout + completed.stderr).strip()[-6000:]}
            except (OSError, subprocess.TimeoutExpired) as exc:
                check = {"name": name, "passed": False, "error_type": type(exc).__name__}
            report["checks"].append(check)
            print(f"{name}: {'PASS' if check['passed'] else 'FAIL'}", flush=True)
        if junit.exists():
            # This file is generated by our pytest subprocess in a private temp
            # directory, never downloaded or accepted from a request.
            suite = ET.parse(junit).getroot().find("testsuite")  # nosec B314
            if suite is not None:
                report["pytest_counts"] = {key: int(suite.attrib[key]) for key in ("tests", "failures", "errors", "skipped")}

    # Targeted production credential patterns; report paths only, never values.
    patterns = [re.compile(rb"sk-(?:proj-)?[A-Za-z0-9_-]{24,}"),
                re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")]
    secret_matches = []
    for path in source_files():
        relative = path.relative_to(ROOT).as_posix()
        content = path.read_bytes()
        digest = hashlib.sha256(content).hexdigest()
        report["source_sha256"][relative] = digest
        if path.parts[len(ROOT.parts)] in {"app", "supabase"} and any(pattern.search(content) for pattern in patterns):
            secret_matches.append(relative)
        if args.baseline:
            old = args.baseline / relative
            original = hashlib.sha256(old.read_bytes()).hexdigest() if old.is_file() else None
            if original != digest:
                report["changed_from_baseline"].append({"path": relative, "before_sha256": original, "after_sha256": digest})
    report["checks"].append({"name": "targeted_secret_patterns", "passed": not secret_matches, "matched_paths": secret_matches})
    report["passed"] = all(check["passed"] for check in report["checks"])
    report["postgres_requested"] = args.postgres
    report["known_follow_up"] = "Pinned Starlette 1.6.0 warns about HTTPX TestClient compatibility. Track separately; no dependency upgrade or warning suppression in this patch."
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Verification artifact: {output}")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
