-- Server-only login/signup abuse limits keyed by HMAC identifiers. Raw email
-- addresses and client IP values are never stored in this ledger.

create table if not exists public.pre_auth_rate_events (
  id bigint generated by default as identity primary key,
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  bucket text not null check (char_length(bucket) between 1 and 80),
  occurred_at timestamptz not null default now()
);

create index if not exists pre_auth_rate_events_lookup_idx
  on public.pre_auth_rate_events (key_hash, bucket, occurred_at desc);

alter table public.pre_auth_rate_events enable row level security;
revoke all on table public.pre_auth_rate_events from anon, authenticated;
grant select, insert, delete on table public.pre_auth_rate_events to service_role;

drop policy if exists pre_auth_rate_events_customer_deny on public.pre_auth_rate_events;
create policy pre_auth_rate_events_customer_deny
  on public.pre_auth_rate_events
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

create or replace function public.killgate_pre_auth_rate_limit_allow(
  p_key_hash text,
  p_bucket text,
  p_max integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  event_count integer;
  cutoff timestamptz;
begin
  if p_key_hash is null
     or p_key_hash !~ '^[0-9a-f]{64}$'
     or p_bucket is null
     or char_length(p_bucket) < 1
     or char_length(p_bucket) > 80
     or p_max < 1
     or p_max > 10000
     or p_window_seconds < 1
     or p_window_seconds > 604800 then
    return false;
  end if;

  cutoff := now() - make_interval(secs => p_window_seconds);
  perform pg_advisory_xact_lock(hashtextextended(p_key_hash || ':' || p_bucket, 0));

  delete from public.pre_auth_rate_events
   where key_hash = p_key_hash
     and bucket = p_bucket
     and occurred_at <= cutoff;

  select count(*)
    into event_count
    from public.pre_auth_rate_events
   where key_hash = p_key_hash
     and bucket = p_bucket
     and occurred_at > cutoff;

  if event_count >= p_max then
    return false;
  end if;

  insert into public.pre_auth_rate_events (key_hash, bucket)
  values (p_key_hash, p_bucket);
  return true;
end;
$$;

revoke all on function public.killgate_pre_auth_rate_limit_allow(text, text, integer, integer) from public;
revoke all on function public.killgate_pre_auth_rate_limit_allow(text, text, integer, integer) from anon, authenticated;
grant execute on function public.killgate_pre_auth_rate_limit_allow(text, text, integer, integer) to service_role;
