-- Server-only distributed sliding-window limits for production Killgate instances.
-- Customer roles cannot read or write the event ledger or execute the RPC.

create table if not exists public.request_rate_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bucket text not null check (char_length(bucket) between 1 and 80),
  occurred_at timestamptz not null default now()
);

create index if not exists request_rate_events_lookup_idx
  on public.request_rate_events (user_id, bucket, occurred_at desc);

alter table public.request_rate_events enable row level security;

revoke all on table public.request_rate_events from anon, authenticated;
grant select, insert, delete on table public.request_rate_events to service_role;

-- An explicit deny policy documents the customer boundary and keeps the RLS
-- security advisor from treating the server-only table as accidentally policy-less.
drop policy if exists request_rate_events_customer_deny on public.request_rate_events;
create policy request_rate_events_customer_deny
  on public.request_rate_events
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

create or replace function public.killgate_rate_limit_allow(
  p_user_id uuid,
  p_bucket text,
  p_max integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  event_count integer;
  cutoff timestamptz;
begin
  if p_user_id is null
     or p_bucket is null
     or char_length(p_bucket) < 1
     or char_length(p_bucket) > 80
     or p_max < 1
     or p_max > 10000
     or p_window_seconds < 1
     or p_window_seconds > 604800 then
    return false;
  end if;

  cutoff := now() - make_interval(secs => p_window_seconds);

  -- Serialize each user/bucket window so parallel app workers cannot both see
  -- the same pre-insert count and exceed the configured cap.
  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || p_bucket, 0)
  );

  delete from public.request_rate_events
   where user_id = p_user_id
     and bucket = p_bucket
     and occurred_at <= cutoff;

  select count(*)
    into event_count
    from public.request_rate_events
   where user_id = p_user_id
     and bucket = p_bucket
     and occurred_at > cutoff;

  if event_count >= p_max then
    return false;
  end if;

  insert into public.request_rate_events (user_id, bucket) values (p_user_id, p_bucket);
  return true;
end;
$$;

revoke all on function public.killgate_rate_limit_allow(uuid, text, integer, integer) from public;
revoke all on function public.killgate_rate_limit_allow(uuid, text, integer, integer) from anon, authenticated;
grant execute on function public.killgate_rate_limit_allow(uuid, text, integer, integer) to service_role;
